go-auth0/auth0

management/connection.go

Hi there,
I have added some more options for waad connection as required by my use case.
I'd love to hear from @alexkappa what he thinks?

add ConnectionWaadOptions

---

management/connection.go

- enableDatabaseCustomization
- brut_force_protection
- import_mode
- disable_signup

add some attributes to the Options of a Connection

---

management/connection.go

brut_force_protection -> brute_force_protection

fix typo on Connection options attribute

---

management/user.go
management/user_test.go

Fixes https://github.com/yieldr/go-auth0/issues/17

Fix required connection field for User

---

management/grant.go

Allow parameters for the List methods in order to be able to
retreieve grants for a given user, or paginate result.

Add parameter support for the Grant list metods

---

README.md
management/user.go
management/user_test.go

This PR is based on branch `roles`.
Adding functionality to User
- GetRoles
- AssignRole
- UnassignRoles

Support roles to users

---

management/connection.go

There are a few non-documented options to integrate with Twilio. This PR is to add those options on the SDK and eventually add them to the terraform provider as well.
More info https://community.auth0.com/t/using-management-api-to-create-a-twilio-connection/23576/3

Added options to integrate with Twilio

---

management/user.go

Added support for User identities field

---

README.md
management/branding.go
management/branding_test.go
management/management.go

For the tests, I add to check the selected scopes of the API Explorer Application in "Machine to Machine Application" settings Auth0 Management API.
Here the issue that helps me: https://community.auth0.com/t/auth0-management-api-api-explorer-miss-branding-scopes/28026

add Branding resource

---

management/resource_server.go

https://auth0.com/docs/api/management/v2#!/Resource_Servers/patch_resource_servers_by_id

Add enforce_policies field to resource server

---

management/branding_test.go
management/tenant.go
management/tenant_test.go

- idle_session_lifetime
- universal_login
- enabled_locales
- device_flow
and flags :
- enable_sso
- allow_changing_enable_sso
- universal_login
- enable_legacy_logs_search_v2
- disable_clickjack_protection_headers

Add missing fields in Tenant

---

management/user.go
management/user_test.go

Adds the three endpoints:
* https://auth0.com/docs/api/management/v2#!/Users/get_permissions
* https://auth0.com/docs/api/management/v2#!/Users/post_permissions
* https://auth0.com/docs/api/management/v2#!/Users/delete_permissions

Add user permission endpoints

---

management/client_grant.go
management/client_grant_test.go

Closes https://github.com/go-auth0/auth0/issues/66

Add listing client grants

---

README.md
management/blacklist.go
management/blacklist_test.go
management/management.go

Add blacklist support:
*  get /api/v2/blacklists/tokens https://auth0.com/docs/api/management/v2#!/Blacklists/get_tokens
*  post /api/v2/blacklists/tokens  https://auth0.com/docs/api/management/v2#!/Blacklists/post_tokens

Add blacklist support

---

management/hook.go
management/hook_test.go
management/management.go

add support for the "hook" type

add "hook" support

---

management/grant.go

This PR addresses https://github.com/go-auth0/auth0/issues/90.
I'm new to auth0 and I'm not sure how to consistently test this method.
Specially since the test cases run against an auth0 API and I can't find an easy way to generate grants!

delete a grant by user-id

---

management/connection.go

Introduce new option: strategy_version

---

.github/workflows/codeql.yml

This PR updates the Code Scanning Workflow to include a step which uploads the results. Any findings are then available from the security tab within the repository.

Updated Code Scanning Workflow

---

management/management.gen.go
management/user.go

Add missing user fields present in the API response.

---

management/connection.go
management/connection_test.go
management/management.gen.go

Add support for Oauth2 Connection Strategy

---

internal/client/client.go

I believe them to be equivalent... :)

internal/client: simplify funs passed to rehttp.NewTransport

---

README.md
internal/client/client.go
management/log_stream.go
management/log_stream_test.go
management/management.gen.go
management/management.go

add support for managing log-streams

---

management/connection.go

Required for https://github.com/alexkappa/terraform-provider-auth0/pull/285

Add missing SetUserAttributes to ConnectionOptionsSAML

---

management/connection.go

Fixes https://github.com/go-auth0/auth0/issues/164

Only unmarshal connection options if not nil.

---

management/connection.go
management/management.gen.go

* Adds set_user_root_attributes to other connections
```
...
```

Adds set_user_root_attributes to more connections

---

management/guardian_test.go
management/management.gen.go

This fixes the formatting issue in PR #200 and also makes the new accessors available.

Fix formatting & new accessors for PR #200

---

.github/workflows/go.yml
management/management.gen.go

* Update actions config to validate that, if required, `go generate` has been run.
* Re-run `go generate ./...` to ensure all generated code is up to date.
This change also has the effect of running basic `fmt`/`generate`/`build` validation on all branches/PRs so that issues can be better caught before merging. Acceptance test runs are still reserved for `master` builds as they use secrets and can take a while to run.
The first commit updates the actions config, and you can see it failing. The second commit includes updates from `go generate` that have been missed from previous updates to the library.
```
...
```
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/ …

Update actions config to do fmt/generate/build validation for PRs/branches

---

README.md

change link to godoc from v1 to v5
Just updates one line in  README

change link to godoc from v1 to v5

---

management/management.gen.go
management/user.go

This field can be part of Twitter identities.
https://community.auth0.com/t/how-to-access-to-user-token-and-token-secret-twitter/38524/5

Add AccessTokenSecret to UserIdentity

---

management/management.gen.go

Regenerate accessors for MFA v5 update

---

.gitignore
management/guardian.go
management/guardian_test.go
management/management.gen.go

This adds support for https://auth0.com/docs/api/management/v2#!/Guardian/post_ticket.

ability to create MFA enrollment ticket

---

management/user.go
management/user_test.go

* Add support for https://auth0.com/docs/api/management/v2#!/User_Blocks/get_user_blocks
* Add support for https://auth0.com/docs/api/management/v2#!/User_Blocks/delete_user_blocks
```
```

feat: add user-blocks operations by identifier

---

management/actions.go
management/actions_test.go
management/management.gen.go
management/management.go

* Add support for Auth0 Actions
Fixes #218
<details>
<summary>$ go test ./... -v -run TestActions</summary>
```
$ go test ./... -v -run TestActions
=== RUN   TestActions
--- PASS: TestActions (10.87s)
=== RUN   TestActions/ListTriggers
actions_test.go:55: {
"triggers": [
{
"id": "post-login",
"version": "v1",
"status": "DEPRECATED"
},
{
"id": "post-login",
"version": "v2",
"status": "CURRENT"
},
{
"id": "credentials-exchange",
"version": "v1",
"status": "DEPRECATED"
},
{
"id": "credentials-exchange",
"version": "v2",
"status": "CURRENT"
},
{
"id": "pre-user-registration",
"version": "v1",
"status": "DEPRECATED"
},
{
"id": "pre-user-registration",
"version": "v2",
"status": "CURRENT"
},
{
"id": "post-user-registration",
"version": "v1",
"status": "DEPRECATED"
},
{
"id": …
```

feat: actions support

---

management/connection.go
management/connection_test.go
management/management.gen.go

* Add scope getter/setter to google-apps connection options
```
$ go test ./... -v -run TestConnection
testing: warning: no tests to run
PASS
ok  	gopkg.in/auth0.v5	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	gopkg.in/auth0.v5/internal/client	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	gopkg.in/auth0.v5/internal/tag	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	gopkg.in/auth0.v5/internal/testing/expect	(cached) [no tests to run]
=== RUN   TestConnection
=== RUN   TestConnection/Create
connection_test.go:31: {
"id": "con_q7rPRWu5imhYPqhv",
"name": "Test-Connection-1624265592",
"strategy": "auth0",
"is_domain_connection": false,
"realms": [
"Test-Connection-1624265592"
],
"options": {
"mfa": {
"active": true, …
```

Add scope getter/setter to google-apps connection options

---

management/organization_test.go

* Fix formatting around OrganizationBranding

Fix formatting of OrganizationBranding

---

management/guardian.go
management/guardian_test.go
management/management.gen.go

Adding the ability to enable webauthn roaming and platform
#224 

Issue 224: adding support webauthn roaming and platform

---

management/connection.go
management/management.gen.go

Add show as button field to connection struct.
Used in WEB and not in go lib.

Add show as button field to connection

---

management/actions.go
management/actions_test.go
management/management.gen.go

* Modify `ActionManager` methods to adhere to conventions of the SDK.
* Add `Runtime` field to `Action`
* Add comments to fields.
```
$ go test ./... -run TestAction                                                                                                                                                                                                                                          [17:35:27]
ok      gopkg.in/auth0.v5       (cached) [no tests to run]
ok      gopkg.in/auth0.v5/internal/client       (cached) [no tests to run]
ok      gopkg.in/auth0.v5/internal/tag  (cached) [no tests to run]
ok      gopkg.in/auth0.v5/internal/testing/expect       (cached) [no tests to run]
ok      gopkg.in/auth0.v5/management    8.390s
```
* Please vote on this pull request by adding a 👍 …

Update actions fields and methods
