go-auth0/auth0

management/client.go, management/connection.go, management/custom_domain.go, management/email.go, management/email_template.go, management/management.go, management/management_test.go, management/resource_server.go, management/rule.go
In order to support passing options to the Auth0 API we needed a way to set query parameters to the calls.
This PR adds support for setting such options via optional [functional arguments](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis).
For the time being, options are allowed in most `Read` operations. If its needed in other operations we can examine the use case.
*Warning*: This has a small BC change with the Email Provider resource where we hard coded the options inside the read call. This is now removed.
=> introduce options for configuring api calls

management/connection.go, management/connection_test.go
This variable is currently almost undocumented on auth0, but
it works fine for an auth0 database connection.
=> Add requires_username option to auth0 connection

management/management.go, management/utils.go
Introduce `oauth2.ReuseToken` in order to refresh our access token for long running processes. Fixes #15 
@hypnoglow would you like to give it a try?
=> Use oauth2.ReuseToken to re-authenticate when token becomes invalid

management/connection.go
The API was receiving the property `custom_script`, but it was expecting `customScript`.
The key is not documented in the [get_connections_response_options](https://auth0.com/docs/api/management/v2#!/Connections/get_connections) nor the get_connections_by_id_response_options](https://auth0.com/docs/api/management/v2#!/Connections/get_connections_by_id), so the only way to see it is an API request for a connection with a custom DB script.
=> customScripts was not working with the Auth0 API

management/connection.go
This PR adds ability to specify **is_domain_connection** property for auth0 connections. Only domain level connections can be used with third-party clients.
=> Add IsDomainConnection property to Connection struct

management/client.go
This PR introduces ability to change is_token_endpoint_ip_header_trusted property to clients.
There is no documentation regarding the property, but the api returns and allows to change the value of it.
p.s. I've been told by auth0 support that they will update the documentation
=> Add is_token_endpoint_ip_header_trusted property support to Client

management/connection.go
It's not directly exposed through the Auth0 Dashboard, but it is exposed through the Auth0 Management API.
See https://community.auth0.com/t/change-a-user-email-when-using-custom-database/9567 for details.
=> Added change_email custom script to docs

management/connection.go
This adds support for 2 more connection properties:  bool ext_nested_groups, string max_groups_to_retrieve.  max_groups_to_retrieve is handled as a string in the Auth0 API, but its content is numeric.  Not sure if there is a better way to handle this.
=> Add support for connection properties ext_nested_groups and max_groups_to_retrieve

management/user.go
I've added the `created_at`, `updated_at` and `last_login` fields for [this endpoint](https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id)
=> User timestamps

management/client_grant.go
The auth0 management requires at least an empty list: https://auth0.com/docs/api/management/v2#!/Client_Grants/post_client_grants
=> fix: do not omit empty scope list on client grant

management/user.go, management/user_test.go
The Auth0 API v2 describes an optional `nickname` field in the `user` endpoint
https://auth0.com/docs/api/management/v2#!/Users/get_users
=> Add 'nickname' to user

README.md, management/management.go, management/role.go, management/role_test.go, management/user.go, management/user_test.go
Resolves #35.
Added `Role` and `Permission` entities as well as a `RoleManager` which supports the following functionality:
- `Create`: Creates a role
- `Read`: Reads a role
- `Update`: Updates a role
- `List`: Lists all available roles within the current tenant
- `AssignUsers`: Assigns a user to a role
- `Users`: Lists all the users associated to this role.
- `AssignPermissions`: Assigns a permission to a role
- `Permissions`: Lists all the permissions associated to this role.
- `UnassignPermissions`: Unassigns a permission from a role
- `Delete`: Deletes a role
=> Support for Roles

README.md, management/user.go, management/user_test.go
This PR adds support for [listing users by email](https://auth0.com/docs/api/management/v2#!/Users_By_Email/get_users_by_email).
Usage:
```go
users, err := m.User.ListByEmail("alice@example.com")
```
=> Add support for listing users by email

management/connection.go, management/connection_test.go
This PR adds the `get connections` management API call as a Connection.List method.
More info https://auth0.com/docs/api/management/v2#!/Connections/get_connections
I haven't tested this - could you point me in the right direction on how I can fork/test with my changes locally? Thank you!
=> introduce Connection.List

management/client.go, management/client_test.go
While extending the yieldr auth0 terraform provider to add a new client data resource, I noticed that the auth0 client was ignoring the signing_keys part of the client response. This PR now respects signing_keys in the Auth0 response.
The Auth0 API insists that the field isn't present on submission, so I've written a custom marshaller which makes a copy of the structure and sets the signing_keys field to nil before marshalling.
I was in two (or more...) minds on how to do this.  The usual approach seems to be to duplicate the structure with the necessary json tags, but for such a large structure, that would be a pain to maintain.
Another approach could be to have two structs, one of which omits the field entirely, but that would constitute a breaking change:
```
type ClientPost struct { …
```
=> signing_keys JSON

management/user.go, management/user_test.go
As a user i want to have access to the full user profile.
Reading https://auth0.com/docs/users/references/user-profile-structure we should be able to retrieve given_name and family_name.
=> User add family and given name

management/connection.go, management/connection_test.go, management/job_test.go
The connectionID is hardcoded in Job test.
This fails when another contributor want to execute this on his own tenant.
=> Stabilize job test

internal/client/client.go, management/management.go
This fixes a silent error we were getting when passing the auth0 domain with included web protocol (`https://tenant.auth0.com`)
Changes:
- The code should be now more resilient to this case, but it should still work with the case where the protocol is not specified.
- If an error arises when making a request to auth0, it is no longer silently ignored.
=> Fix domain related error

management/job.go, management/management.go
Check error when creating new http.Request. Otherwise, when terraform apply command fails because of an issue with creating of request, you will get panic instead of nice error. This will instead print actual error so you can see what happened.
=> fix: check error when creating http.Request

management/connection.go
Currently blocks this PR from being merged: https://github.com/alexkappa/terraform-provider-auth0/pull/130
This updates the auth0 module to support this extra option for the Terraform `auth0_connection` resource.
cc @alexkappa
=> [FEATURE] Add parameter missing to use salesforce community connection

management/ticket.go, management/ticket_test.go
Adds `mark_email_as_verified` to the `Ticket` struct allowing generation of password reset tickets to ultimately flag the users email as verified.
As per docs: https://auth0.com/docs/api/management/v2#!/Tickets/post_password_change
=> Tickets: Mark as verified

README.md, management/guardian.go, management/guardian_test.go, management/management.go
Add support for Guardian Factor:
* GET /api/v2/guardian/factors https://auth0.com/docs/api/management/v2#!/Guardian/get_factors
* PUT /api/v2/guardian/factors/{name} https://auth0.com/docs/api/management/v2#!/Guardian/put_factors_by_name
* GET /api/v2/guardian/factors/sms/templates  https://auth0.com/docs/api/management/v2#!/Guardian/get_templates
* PUT  /api/v2/guardian/factors/sms/templates  https://auth0.com/docs/api/management/v2#!/Guardian/put_templates
* GET /api/v2/guardian/factors/push-notification/providers/sns  https://auth0.com/docs/api/management/v2#!/Guardian/get_sns
* PUT /api/v2/guardian/factors/push-notification/providers/sns  https://auth0.com/docs/api/management/v2#!/Guardian/put_sns
* GET /api/v2/guardian/factors/sms/providers/twilio …
=> Add Guardian Factor support

README.md, management/management.go, management/prompt.go, management/prompt_test.go
Adds the Prompt endpoints:
* GET /api/v2/prompts: https://auth0.com/docs/api/management/v2/#!/Prompts/get_prompts
* PATCH	/api/v2/prompts: https://auth0.com/docs/api/management/v2/#!/Prompts/patch_prompts
=> Add prompt support

README.md, management/user.go, management/user_test.go
This change adds support for retrieving a users blocks and unblocking a user. Only the user id variants are implemented, in that at the moment you cannot retrieve blocks by identifier (email, phone number).
See: https://auth0.com/docs/api/management/v2#!/User_Blocks/get_user_blocks
=> Add support for user blocks

.github/workflows/go.yml, README.md, doc.go, go.mod, internal/tag/tag.go, internal/tag/tag_test.go, management/blacklist_test.go, management/branding_test.go, management/client_grant_test.go, management/client_test.go, management/connection.go, management/connection_test.go, management/custom_domain_test.go, management/email_template_test.go, management/email_test.go, management/example_test.go, management/guardian_test.go, management/hook_test.go, management/job_test.go, management/log_test.go, management/management.gen.go, management/management.go, management/resource_server_test.go, management/role_test.go, management/rule_config_test.go, management/rule_test.go, management/tenant_test.go, management/ticket_test.go, management/user_test.go
Due to the way the Auth0 API handles the various options depending on connection strategy, this SDK is no longer able to continue using a single type for `Connection.Options`.
Depending on the strategy, options fields (and their types) can vary. Sometimes fields are re-used and with different data types. For example `options.email` can be a boolean when strategy is `google-oauth2` and an object when strategy is `email`.
In order to avoid such corner cases, I've introduced specific types for each strategy, and made `Connection.Options` an `interface{}` in order to support any one of the available choices.
The following table shows the type which will be used when Unmarshalling.
| Strategy | Type |
| ------- | --------|
| `auth0` | ConnectionOptions |
| `google-oauth2` | …
=> Make ConnectionOptions "polymorphic"

management/user.go, management/user_test.go
Auth0 API has a bug - in some cases it might return `identity.user_id` as a number. Particularly for GitHub identities for requests to the `/users/<user_id` endpoint. In this case JSON unmarshalling will fail with an error: 
`"json: cannot unmarshal number into Go struct field UserIdentity.identities.user_id of type string"`
I created a report in Auth0 community: https://community.auth0.com/t/users-user-id-returns-inconsistent-type-for-identities-user-id/39236
Meanwhile this PR should allow to work around this problem.
=> Workaround for UserIdentity.UserID being a number

management/branding.go, management/branding_test.go, management/management.gen.go
=> Branding: support page_background with gradient

CHANGELOG.md, management/role.go, management/role_test.go, management/user.go, management/user_test.go
This PR adds support for paginating:
- `User.Roles()`
- `User.Permissions()`
- `Role.Users()`
- `Role.Permissions()`
Fixes #108 
**Note**: This is a backwards incompatible change.
=> Paginate when reading role users or user roles

management/connection.go
Auth0 Connections have an optional field Display Name, which is missing from the Connection struct.
fixes: https://github.com/go-auth0/auth0/issues/114
=> Add DisplayName field to the Connection struct

management/connection.go, management/connection_test.go, management/management.gen.go, management/management.go
This PR adds the options for the SAML connection type.
- Added attributes supported by the Management API V2
- Added relevant tests
=> Add mappings for the SAML type connection 

management/client.go, management/management.gen.go, management/management_test.go
Update `ClientRefreshToken` type.
New fields:
- `RotationType`
- `ExpirationType`
Deprecated fields:
- `Type`
=> Update client.refresh_token to allow for rotation_type and expiration_type fields

.github/workflows/codeql.yml, management/client.go, management/connection_test.go, management/management.gen.go
Improve connection options tests.
- Use generated accessors for getting IDs
```diff
- auth0.StringValue(c.ID)
+ c.GetID()
```
- Fix broken deferred deletes by wrapping them in a self invoked function.
```diff
- defer m.Connection.Delete(g.GetID())
+ defer func() { m.Connection.Delete(g.GetID()) }()
```
- Move connection options tests under their own `TestConnectionOptions` test function.
- Various small improvements
=> Improve connection options tests

management/rule.go
This seems to have been a typo.
=> fix: rule list should use `rules` and not `roles`

management/connection.go, management/management.gen.go
Three SAML options got missed when SAML Connection support was re-added to the provider. 
This PR brings parity to what settings can be set with regards to the SAML connection.
=> add missing SAML Connection Options

management/job.go
It fixes issue https://github.com/go-auth0/auth0/issues/153
=> Fixing wrong JSON tag in management.Job

management/connection.go, management/connection_test.go, management/management.gen.go
Fixes #146 
Blocks: https://github.com/alexkappa/terraform-provider-auth0/pull/272
=> fixed wrong property names for tokenURL and authorizationURL

auth0.go, auth0_test.go, management/gen-methods.go, management/management.gen.go, management/tenant.go, management/tenant_test.go
`Tenant` `session_lifetime` and `idle_session_lifetime` are changed to `float64` types.
Also, when `session_lifetime` is less than 1, it is replaced with `session_lifetime_in_minutes` instead, multiplied by 60.
Fixes: #127
=> Send tenant session_lifetime_in_minutes when session_lifetime is < 1

management/user.go
As https://github.com/go-auth0/auth0/issues/100 says,  auth0 management has response of 
`access_token` issued by google.
Without this `access_token`, can't call google's api.
https://auth0.com/docs/tokens/concepts/idp-access-tokens?_ga=2.123250563.948245286.1589091717-1358488943.1589091717#renew-tokens
=> Add access_token of UserIdentity for google social connection

management/hook.go
=> HookManager.List used wrong endpoint ('roles' instead of 'hooks')

management/management.go, management/user.go, management/user_test.go
Opening PR since looks to be the only way of running tests. Pending to verify if the feature works
=> Add post_identities endpoint support

management/client.go
Add support for more refresh_token fields supported by the api:
```
infinite_token_lifetime
infinite_idle_token_lifetime
idle_token_lifetime
```
https://auth0.com/docs/api/management/v2#!/Clients/post_clients
Closes #183
=> Add addition client refresh_token fields

management/management.gen.go, management/ticket.go, management/ticket_test.go
Adds the missing field `IncludeEmailInRedirect` to `management.Ticket`. 
ref: https://auth0.com/docs/api/management/v2#!/Tickets/post_password_change
=> Add missing field IncludeEmailInRedirect to Ticket

management/user.go
Add support for reading refresh token on UserIdentity.
Based on: https://auth0.com/docs/tokens/identity-provider-access-tokens#renew-third-party-tokens
=> Add refreshToken field on UserIdentity

management/connection.go, management/connection_test.go
* ConnectionManager.ReadByName() function returns an error if the `name` parameter is empty.
Fixes #185 
```
$ go test ./... -v -run TestConnection
...
```
=> #185: Assert name is not empty in connection.ReadByName function

management/connection.go, management/management.gen.go
* Adds missing SetUserAttributes in the ConnectionOptions
```
...
```
=> Adds SetUserAttributes to ConnectionOptions

management/connection.go, management/management.gen.go
The AzureAD connection type has an advanced option that is currently missing from this API.
It lets you choose whether or not to set the email_verified to true when a new user connects.
Due to the complexities of the azure connections, there are ramifications to setting this which are explained in the auth0 docs.
Adding the extra optional attribute in here so that it can be subsequently added to the terraform provider.
* add optional TrustEmailVerified option to the AzureAD connection object
Unfortunately there are currently no AzureAD specific tests, so nothing to modify.
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and …
=> fix: add missing AzureAD connection option

management/guardian.go, management/guardian_test.go
We can now update MFA policy and some settings regarding what provider and message type we use.
Fixes #199
```
$ go test ./management -v -run "TestGuardian/MultiFactor/Phone"
...
$ go test ./management -v -run "TestGuardian/MultiFactor/Policy"
```
=> Extended MFA api

management/log.go, management/management.gen.go
* `description` is added in the `Log` struct
* sync'ed accessors with `gen-methods`
<details>
<summary>$ go test ./... -v -run TestLog</summary>
```
=== RUN   TestLog
=== RUN   TestLog/List
log_test.go:24: {
"_id": "90020210126192811425000155054908796690747930870001172578",
"log_id": "90020210126192811425000155054908796690747930870001172578",
"date": "2021-01-26T19:28:06.431Z",
"type": "sapi",
"description": "Create a log stream",
"client_id": "<client_id_redacted>",
"client_name": "",
"ip": "<ip_redacted>",
"location_info": null,
"details": {
"request": {
"auth": {
"credentials": {},
"strategy": "jwt",
"user": {}
},
"body": {
"name": "Test-LogStream-1611689286",
"sink": {
"awsRegion": "us-west-2"
},
"type": "eventbridge"
},
"channel": "api",
"ip": "<ip_redacted>",
"method": "post", …
```
=> Add description field to logs

management/connection.go, management/connection_test.go
First off, I have no experience in GoLang so I'm not sure this is the correct solution to this problem.  Please let me know if anything needs to be changed with this PR.
This is step one of me attempting to fix an issue with the terraform provider that utilizes this library. 
[Issue 282 on alexkappa/terraform-provider-auth0](https://github.com/alexkappa/terraform-provider-auth0/issues/282)
When attempting to fix that in the terraform provider I noticed that the data type for the property was an interface pointer which doesn't make sense to me.
I think the Metadata property on connection should be the same data type as "client_metadata" would be on an application/client since connection metadata functions in exactly the same way as client metadata.  I changed it to map[string]string …
=> Updated Metadata property on connection to be string map

management/management.gen.go, management/user.go
See https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/user
Here's the raw JSON for my Twitter account copied from the Auth0 console:
```
{
"created_at": "2021-02-09T17:32:08.973Z",
"description": "Freelance cloud consultant by day. Aspiring product builder by night.",
"identities": [
{
"provider": "twitter",
"user_id": "295919262",
"connection": "twitter",
"isSocial": true
}
],
"location": "Hamburg 🇩🇪",
"name": "Mathias Lafeldt",
"nickname": "Mathias Lafeldt",
"picture": "https://pbs.twimg.com/profile_images/1069419719227146240/e8l9msvL_normal.jpg",
"screen_name": "mlafeldt",
"updated_at": "2021-02-11T08:56:51.590Z",
"url": "https://t.co/jXqmcnVmL5",
"user_id": "twitter|295919262",
"blocked": false,
"last_ip": "1.2.3.4",
"last_login": …
```
=> Add missing user fields provided by Twitter

management/connection.go, management/connection_test.go, management/management.gen.go
* Add ProvisioningTicketUrl to property of management.Connection.
This item is not listed in the API documentation, but it is issued in some strategies such as "ad".
```
{
"id":"con_xxxx",
"options":{
"certAuth":false,
"disable_cache":false,
"kerberos":false,
"domain_aliases":[
"idp-domain.com"
],
"tenant_domain":"xyz-domain.com",
"ips":null,
"brute_force_protection":true
},
"strategy":"ad",
"name":"xyz-test-ad-conn",
"provisioning_ticket_url":"https://xyz-dev.us.auth0.com/p/ad/xxxx",
"is_domain_connection":false,
"show_as_button":false,
"display_name":"Xyz-Test-Ad-Conn",
"enabled_clients":[],
"realms":[
"xyz-test-ad-conn"
]
}
```
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the …
=> add ProvisioningTicketUrl to Connection

management/management.gen.go, management/prompt.go, management/prompt_test.go
Adds the new `identifier_first` argument to prompts. I will update the terraform provider as well once this lands and is tagged.
https://support.auth0.com/notifications/5fff0ab3f28427000a77941e
```
kpurdon@syndio: ~/.../kpurdon/auth0 go test ./... -v -run TestPrompt
testing: warning: no tests to run
PASS
ok  	gopkg.in/auth0.v5	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	gopkg.in/auth0.v5/internal/client	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	gopkg.in/auth0.v5/internal/tag	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	gopkg.in/auth0.v5/internal/testing/expect	(cached) [no tests to run]
=== RUN   TestPrompt
=== RUN   TestPrompt/Read
prompt_test.go:14: {
"universal_login_experience": "classic"
}
=== RUN …
```
=> Add the new identifier_first argument to prompts

README.md, management/management.gen.go, management/management.go, management/management_test.go, management/signing_key.go, management/signing_key_test.go
This PR adds [application signing key endpoints](https://auth0.com/docs/api/management/v2#!/Keys/get_signing_keys) to the SDK.
**NOTE:** There are a bunch of unrelated `go generate` changes that I'd like to resolve in https://github.com/go-auth0/auth0/pull/189 first (then rebase this one).
```
$ go test ./... -v -run TestKey
ok  	gopkg.in/auth0.v5	(cached) [no tests to run]
ok  	gopkg.in/auth0.v5/internal/client	(cached) [no tests to run]
ok  	gopkg.in/auth0.v5/internal/tag	(cached) [no tests to run]
ok  	gopkg.in/auth0.v5/internal/testing/expect	(cached) [no tests to run]
ok  	gopkg.in/auth0.v5/management	1.780s
...
```
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull …
=> Add application signing key endpoints

management/grant.go, management/grant_test.go, management/management.gen.go
* Have Grant List also use applyListDefaults.
Fixes #168 
```
go test ./... -v -run TestGrant                                     
=== RUN   TestGrant
=== RUN   TestGrant/List
grant_test.go:15: []
--- PASS: TestGrant (0.47s)
--- PASS: TestGrant/List (0.47s)
PASS
ok  	gopkg.in/auth0.v5/management	(cached)
```
=> Have Grant List also use applyListDefaults.

go.mod, management/connection.go, management/connection_test.go, management/management.gen.go
As described in https://auth0.com/docs/security/denylist-user-attributes there exists an option to add a DenyList on all connections such that  some user data fields are never stored in auth0. This PR adds the ability to include this in the request to update connections.
* Adds extra field of `NonPersistentAttrs     *[]string ` to all `Connection` structs
```
$ go test ./... -v -run TestConnection
```
=> Added denylist options for the connections

management/connection.go, management/management.gen.go
* Add `EntityID` field to the `ConnectionOptionsSAML` structure which maps to the `options.entityId` field of the Auth0 Connection object for SAML connections.
```
$ go test ./... -v -run TestConnection
...
```
=> Add support for Auth0 SAML connection entityId option

.gitignore, README.md, go.mod, go.sum, management/management_test.go
* Add support for using a local `.env` to drive configuration (vs. having to `export` variables explicitly)
* Nothing happens if the `.env` does not exist
* Enhanced README.md to suggest using the `.env` file
```
$ go test ./... -v
...
```
=> Add .env config file support

management/guardian.go, management/guardian_test.go
This is a bugfix to a bug that was introduced in #200. This PR resolves the bug and adds a test that would have caught the bug in the first place.
* Resolves bug when reading policy of MFA options back from auth0
```
$ go test ./management -v -run "TestGuardian/MultiFactor/Policy"
```
=> Fixed minor bug when unmarshalling Policy string array

management/connection.go, management/connection_test.go, management/management.gen.go
I'm still wrapping my head around the repo (and golang in general) so thanks for your patience with any simple mistakes 🙏 
* Adds a new connection strategy for `google-apps` connections
I expected the error below to go away after setting up a test tenant and putting the domain in `.env`. Unsure what mistake I'm making here.
```
testing: warning: no tests to run
PASS
ok      gopkg.in/auth0.v5       (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      gopkg.in/auth0.v5/internal/client       (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      gopkg.in/auth0.v5/internal/tag  (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      gopkg.in/auth0.v5/internal/testing/expect       (cached) [no tests to …
```
=> Support google-apps connection strategy

management/client.go, management/client_test.go
The Management API returns a `string` for `jwt_configuration.lifetime_in_seconds` instead of an `int` for some old tenants.
This PR implements a custom JSON marshaler and unmarshaler for `ClientJWTConfiguration` that addresses this.
Fixes https://github.com/auth0/auth0-cli/issues/274
```
go test -run TestJWTConfiguration gopkg.in/auth0.v5/management
```
=> Fix JSON encode/decode of lifetime_in_seconds

management/anomaly.go, management/anomaly_test.go, management/management.go
This PR adds support for the two Anomaly endpoints:
- `GET	/api/v2/anomaly/blocks/ips/{id}`: https://auth0.com/docs/api/management/v2#!/Anomaly/get_ips_by_id
- `DELETE	/api/v2/anomaly/blocks/ips/{id}`: https://auth0.com/docs/api/management/v2#!/Anomaly/delete_ips_by_id
The GET endpoint, unlike the other API2 endpoints, takes no data in the request body and returns no data in the response body (except in the case of error). The only input is an IP address passed as part of the path, and the outcome of the operation is signaled by status codes.
A status code of `200` means that the IP is blocked, and a status code of `404` means that it is not blocked.
The current request-making logic does not expose the status code, and returning the error does not make sense as a `404`  will end up as an …
=> Add support for Anomaly endpoints

README.md, management/custom_domain.go, management/custom_domain_test.go, management/management.gen.go
This PR adds the [update](https://auth0.com/docs/api/management/v2#!/Custom_Domains/patch_custom_domains_by_id) method to the custom domain manager, along with the 2 properties that can be updated:
- TLS policy
- Custom Client IP header
This has been tested manually on a modified Auth0 CLI.
=> Add update method to custom domain manager

management/client.go, management/management.gen.go, management/management.go, management/organization.go, management/organization_test.go, management/user.go
* Implements Organizations Management API
```
$ go test ./... -v -run TestOrganization
=== RUN   TestOrganization
--- FAIL: TestOrganization (12.71s)
=== RUN   TestOrganization/Create
organization_test.go:98: {
"id": "org_862pZwOTjQgrkHOM",
"name": "testorganization20210514011508",
"display_name": "Test Organization",
"branding": {
"logo_url": "https://example.com/logo.gif"
}
}
--- PASS: TestOrganization/Create (0.33s)
=== RUN   TestOrganization/List
organization_test.go:108: {
"start": 0,
"limit": 50,
"length": 0,
"total": 1,
"organizations": [
{
"id": "org_862pZwOTjQgrkHOM",
"name": "testorganization20210514011508",
"display_name": "Test Organization",
"branding": {
"logo_url": "https://example.com/logo.gif"
}
}
]
}
--- PASS: TestOrganization/List (0.20s)
=== RUN …
```
=> Implement Organizations Management API

README.md
Go requires quotes around import paths. Add some quotes so the example compiles!
=> Fix import syntax in README

management/connection.go, management/connection_test.go
It seems the option is actually `ext_is_admin` instead of `ext_admin` for at least google-apps conn types. 
```
=== RUN   TestConnectionOptions
--- PASS: TestConnectionOptions (2.67s)
=== RUN   TestConnectionOptions/GoogleApps
--- PASS: TestConnectionOptions/GoogleApps (2.67s)
PASS
...
```
=> Fix ext_is_admin option on google-apps conn type

management/connection_test.go
This fixes: https://github.com/go-auth0/auth0/runs/4142950052?check_suite_focus=true
```
=== RUN   TestConnectionOptions
--- PASS: TestConnectionOptions (1.75s)
=== RUN   TestConnectionOptions/CustomSMS
--- PASS: TestConnectionOptions/CustomSMS (1.75s)
PASS
...
```
=> Fix expectation in custom sms conn test
